# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('action', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostika yakunlandi'), ('LESSON', "Dars o'zlashtirildi"), ('SUBMISSION', 'Topshiriq yuborildi'), ('REFLECTION', 'Refleksiya yozildi'), ('GOAL', 'Maqsad belgilandi'), ('GOAL_TASK', 'Maqsad vazifasi bajarildi'), ('DAILY', 'Kunlik 15 daqiqa bajarildi'), ('BADGE', 'Nishon olindi')], db_index=True, max_length=20)),
                ('object_ref', models.CharField(blank=True, max_length=200, verbose_name='obyekt')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='faollik bali')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'faollik yozuvi',
                'verbose_name_plural': 'faollik jurnali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('current', models.PositiveIntegerField(default=0, verbose_name='joriy')),
                ('longest', models.PositiveIntegerField(default=0, verbose_name='eng uzun')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='oxirgi faol kun')),
                ('total_active_days', models.PositiveIntegerField(default=0, verbose_name='jami faol kunlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'muntazamlik',
                'verbose_name_plural': 'muntazamlik',
            },
        ),
        migrations.CreateModel(
            name='ComponentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], max_length=3, verbose_name='komponent')),
                ('value', models.FloatField(default=0.0, verbose_name='ball (%)')),
                ('diagnostic_part', models.FloatField(blank=True, null=True, verbose_name='diagnostika ulushi')),
                ('practice_part', models.FloatField(blank=True, null=True, verbose_name='amaliyot ulushi')),
                ('sample_size', models.PositiveIntegerField(default=0, verbose_name='hisobga olingan ish soni')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hisoblangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'komponent bali',
                'verbose_name_plural': 'komponent ballari',
                'constraints': [models.UniqueConstraint(fields=('user', 'component'), name='uniq_user_component')],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], max_length=3)),
                ('done', models.BooleanField(default=False, verbose_name='bajarildi')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, verbose_name='qisqa izoh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kunlik topshiriq',
                'verbose_name_plural': 'kunlik topshiriqlar',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_user_daily_task')],
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='sana')),
                ('mot', models.FloatField(default=0)),
                ('cog', models.FloatField(default=0)),
                ('act', models.FloatField(default=0)),
                ('ref', models.FloatField(default=0)),
                ('cre', models.FloatField(default=0)),
                ('sdi', models.FloatField(default=0, verbose_name='SDI')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rivojlanish kesmasi',
                'verbose_name_plural': 'rivojlanish kesmalari',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_user_snapshot_date')],
            },
        ),
    ]
