# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=250, verbose_name='maqsad')),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], default='ACT', max_length=3, verbose_name="yo'naltirilgan komponent")),
                ('why', models.TextField(blank=True, verbose_name='nima uchun bu maqsad?')),
                ('resources', models.TextField(blank=True, verbose_name='resurslar')),
                ('expected_result', models.TextField(blank=True, verbose_name='kutilayotgan natija')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='boshlanish')),
                ('deadline', models.DateField(verbose_name='muddat')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('DONE', 'Yakunlangan'), ('DROPPED', "To'xtatilgan")], default='ACTIVE', max_length=8)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_comment', models.TextField(blank=True, verbose_name='mentor izohi')),
                ('mentor_approved', models.BooleanField(default=False, verbose_name='mentor tasdiqladi')),
                ('mentor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'maqsad',
                'verbose_name_plural': 'maqsadlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('title', models.CharField(max_length=250, verbose_name='vazifa')),
                ('week', models.PositiveSmallIntegerField(default=1, verbose_name='hafta')),
                ('is_done', models.BooleanField(default=False, verbose_name='bajarildi')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goals.goal')),
            ],
            options={
                'verbose_name': 'maqsad vazifasi',
                'verbose_name_plural': 'maqsad vazifalari',
                'ordering': ['week', 'order', 'id'],
            },
        ),
    ]
