# Generated by Django 6.1.1 on 2026-09-07 08:42

import accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email tasdiqlangan')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='oxirgi IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80, verbose_name='harakat')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='obyekt')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='tafsilot')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit yozuvi',
                'verbose_name_plural': 'audit jurnali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email tasdiqlash',
                'verbose_name_plural': 'email tasdiqlashlar',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('name', models.CharField(max_length=120, verbose_name='guruh nomi')),
                ('otm', models.CharField(blank=True, max_length=200, verbose_name='OTM')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='fakultet')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='kurs')),
                ('invite_code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='guruh kodi')),
                ('study_arm', models.CharField(choices=[('E', 'Tajriba guruhi'), ('C', 'Nazorat guruhi'), ('N', 'Tadqiqotdan tashqari')], default='N', max_length=1, verbose_name='tadqiqot guruhi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
            ],
            options={
                'verbose_name': "o'quv guruhi",
                'verbose_name_plural': "o'quv guruhlari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('role', models.CharField(choices=[('STUDENT', 'Talaba'), ('TEACHER', "O'qituvchi / mentor"), ('RESEARCHER', 'Tadqiqotchi'), ('METHODIST', 'Kontent-metodist'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=20, verbose_name='rol')),
                ('otm', models.CharField(blank=True, max_length=200, verbose_name='OTM')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='fakultet')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kurs')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, verbose_name='qisqacha')),
                ('research_consent', models.BooleanField(default=False, verbose_name='tadqiqotda ishtirok roziligi')),
                ('research_consent_at', models.DateTimeField(blank=True, null=True)),
                ('respondent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='respondent ID')),
                ('onboarding_done', models.BooleanField(default=False, verbose_name='onboarding tugallangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.studygroup', verbose_name='guruh')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profillar',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="qo'shilgan")),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studygroup')),
            ],
            options={
                'verbose_name': "guruh a'zoligi",
                'verbose_name_plural': "guruh a'zoliklari",
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'group'), name='uniq_active_enrollment')],
            },
        ),
    ]
