# Generated by Django 6.1.1 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studygroup_invite_code'),
        ('assignments', '0002_assignedtask_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='uniq_active_enrollment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.AddField(
            model_name='profile',
            name='study_arm',
            field=models.CharField(choices=[('E', "Tajriba bo'linmasi"), ('C', "Nazorat bo'linmasi"), ('N', 'Tadqiqotdan tashqari')], default='N', max_length=1, verbose_name="tadqiqot bo'linmasi"),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
