# Generated by Django 6.1.1 on 2026-09-11 04:14

from django.db import migrations, models


def fill_roles(apps, schema_editor):
    """Mavjud profillarga berilgan rollar: joriy rol; superuser'ga ADMIN ham."""
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.select_related("user"):
        roles = {profile.role}
        if profile.user.is_superuser:
            roles.add("ADMIN")
        profile.roles = ",".join(r for r in ["TEACHER", "ADMIN"] if r in roles)
        profile.save(update_fields=["roles"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_simplify_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='berilgan rollar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('TEACHER', "O'qituvchi"), ('ADMIN', 'Administrator')], default='TEACHER', max_length=20, verbose_name='faol rol'),
        ),
        migrations.RunPython(fill_roles, migrations.RunPython.noop),
    ]
