# Generated by Django 6.1.1 on 2026-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True, verbose_name='band kaliti')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'menyu bandi',
                'verbose_name_plural': 'menyu tartibi',
                'ordering': ['order'],
            },
        ),
    ]
