# Generated by Django 6.1.1 on 2026-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='guruh kaliti')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tartib')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='sarlavha')),
            ],
            options={
                'verbose_name': 'menyu guruhi',
                'verbose_name_plural': 'menyu guruhlari',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'menyu bandi', 'verbose_name_plural': 'menyu bandlari'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='label',
            field=models.CharField(blank=True, help_text="Bo'sh — standart nom.", max_length=60, verbose_name='nom'),
        ),
    ]
