# Generated by Django 6.1.1 on 2026-09-11 13:07

import django.db.models.deletion
from django.db import migrations, models


def seed_menu(apps, schema_editor):
    """
    Menyu endi to'liq bazada: standart bloklar va bandlar yoziladi. Mavjud tartib,
    nom va sarlavhalar saqlanadi; eski katalogdagi (endi yo'q) yozuvlar o'chiriladi.
    """
    from accounts.menu import DEFAULT_GROUPS, seed_defaults

    MenuGroup = apps.get_model("accounts", "MenuGroup")
    MenuItem = apps.get_model("accounts", "MenuItem")
    seed_defaults(MenuGroup, MenuItem)
    MenuItem.objects.filter(group__isnull=True).delete()
    MenuGroup.objects.exclude(key__in=list(DEFAULT_GROUPS)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_menu_labels_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menugroup',
            options={'ordering': ['order', 'id'], 'verbose_name': 'menyu guruhi', 'verbose_name_plural': 'menyu guruhlari'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'menyu bandi', 'verbose_name_plural': 'menyu bandlari'},
        ),
        migrations.AddField(
            model_name='menugroup',
            name='audience',
            field=models.CharField(choices=[('teacher', "O'qituvchi menyusi"), ('admin', 'Admin menyusi')], default='teacher', max_length=8, verbose_name='menyu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.menugroup', verbose_name='blok'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='hint',
            field=models.CharField(blank=True, max_length=60, verbose_name='izoh'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text="Bo'sh — sahifa ikonkasi.", max_length=20, verbose_name='ikonka'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.CharField(blank=True, max_length=60, verbose_name='sahifa'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.menuitem', verbose_name='ota band'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=300, verbose_name='havola'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(blank=True, help_text="Bo'sh — sahifaning standart nomi.", max_length=60, verbose_name='nom'),
        ),
        migrations.RunPython(seed_menu, migrations.RunPython.noop),
    ]
