# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('text', models.TextField(verbose_name='savol matni')),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], max_length=3, verbose_name='komponent')),
                ('bloom_level', models.PositiveSmallIntegerField(choices=[(1, 'Bilaman'), (2, 'Tushunaman'), (3, "Qo'llayman"), (4, 'Tahlil qilaman'), (5, 'Baholayman'), (6, 'Yarataman')], default=1, verbose_name='Bloom darajasi')),
                ('reverse_scored', models.BooleanField(default=False, help_text="FR-09 — 'Men ... qilmayman' tipidagi savollar uchun.", verbose_name='teskari baholanadi')),
                ('explanation', models.TextField(blank=True, verbose_name="izoh / to'g'ri javob sharhi")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'savol',
                'verbose_name_plural': 'savollar',
                'ordering': ['questionnaire', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('kind', models.CharField(choices=[('LIKERT', "Likert anketa (o'z-o'zini baholash)"), ('TEST', 'Bilim testi')], max_length=10, verbose_name='turi')),
                ('cut', models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-oraliq'), ('INTERIM_2', '2-oraliq'), ('FINAL', 'Yakuniy')], default='INITIAL', max_length=12, verbose_name='kesim')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('instruction', models.TextField(blank=True, verbose_name="ko'rsatma")),
                ('question_count', models.PositiveSmallIntegerField(default=0, help_text='0 — barcha savollar. Testda tasodifiy tanlanma uchun ishlatiladi (FR-08).', verbose_name='tanlanadigan savollar soni')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='vaqt limiti (daq.)')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='savollarni aralashtirish')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': "so'rovnoma",
                'verbose_name_plural': "so'rovnomalar",
                'ordering': ['cut', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='ScoringWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(default='Standart', max_length=120, verbose_name='nomi')),
                ('mot', models.FloatField(default=0.15, verbose_name='MOT vazni')),
                ('cog', models.FloatField(default=0.25, verbose_name='COG vazni')),
                ('act', models.FloatField(default=0.25, verbose_name='ACT vazni')),
                ('ref', models.FloatField(default=0.2, verbose_name='REF vazni')),
                ('cre', models.FloatField(default=0.15, verbose_name='CRE vazni')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'vaznlar profili',
                'verbose_name_plural': 'vaznlar profillari',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('cut', models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-oraliq'), ('INTERIM_2', '2-oraliq'), ('FINAL', 'Yakuniy')], default='INITIAL', max_length=12, verbose_name='kesim')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Jarayonda'), ('FINISHED', 'Yakunlangan'), ('EXPIRED', 'Vaqti tugagan')], default='IN_PROGRESS', max_length=12)),
                ('question_order', models.JSONField(blank=True, default=list, verbose_name='savollar tartibi')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scores', models.JSONField(blank=True, default=dict, verbose_name='komponent natijalari')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='diagnostics.questionnaire')),
            ],
            options={
                'verbose_name': 'urinish',
                'verbose_name_plural': 'urinishlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('cut', models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-oraliq'), ('INTERIM_2', '2-oraliq'), ('FINAL', 'Yakuniy')], max_length=12, verbose_name='kesim')),
                ('mot', models.FloatField(default=0)),
                ('cog', models.FloatField(default=0)),
                ('act', models.FloatField(default=0)),
                ('ref', models.FloatField(default=0)),
                ('cre', models.FloatField(default=0)),
                ('sdi', models.FloatField(default=0, verbose_name='SDI')),
                ('weights_json', models.JSONField(default=dict, verbose_name='ishlatilgan vaznlar')),
                ('source', models.CharField(default='diagnostics', max_length=40, verbose_name='manba')),
                ('is_void', models.BooleanField(default=False, verbose_name='bekor qilingan')),
                ('void_reason', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "o'lchov",
                'verbose_name_plural': "o'lchovlar",
                'ordering': ['user', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('text', models.CharField(max_length=500, verbose_name='variant')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='diagnostics.question')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variantlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Likert qiymati (1-5)')),
                ('text_answer', models.TextField(blank=True, verbose_name='matnli javob')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.attempt')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='diagnostics.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='diagnostics.question')),
            ],
            options={
                'verbose_name': 'javob',
                'verbose_name_plural': 'javoblar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.questionnaire'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], max_length=3)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='diagnostics.measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tavsiya',
                'verbose_name_plural': 'tavsiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['user', 'cut'], name='diagnostics_user_id_ba90ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_question'),
        ),
    ]
