# Generated by Django 6.1.1 on 2026-09-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='kind',
            field=models.CharField(choices=[('LIKERT', "Likert anketa (o'z-o'zini baholash)"), ('TEST', 'Bilim testi'), ('QUIZ', 'Dars mustahkamlash testi')], max_length=10, verbose_name='turi'),
        ),
    ]
