# Generated by Django 6.1.1 on 2026-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_lesson_quiz_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='cut',
            field=models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-chorak'), ('INTERIM_2', '2-chorak'), ('FINAL', 'Yakuniy')], default='INITIAL', max_length=12, verbose_name='kesim'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cut',
            field=models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-chorak'), ('INTERIM_2', '2-chorak'), ('FINAL', 'Yakuniy')], max_length=12, verbose_name='kesim'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cut',
            field=models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-chorak'), ('INTERIM_2', '2-chorak'), ('FINAL', 'Yakuniy')], default='INITIAL', max_length=12, verbose_name='kesim'),
        ),
    ]
