# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], default='ACT', max_length=3)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'kompetensiya bandi',
                'verbose_name_plural': 'kompetensiya checklisti',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=200, verbose_name='rubrika')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'rubrika',
                'verbose_name_plural': 'rubrikalar',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='mezon')),
                ('hint', models.CharField(blank=True, max_length=300, verbose_name='izoh')),
                ('weight', models.FloatField(default=1.0, verbose_name='vazn')),
                ('max_score', models.PositiveSmallIntegerField(default=4, verbose_name='maksimal ball')),
                ('level_descriptions', models.JSONField(blank=True, default=dict, help_text='Masalan: {"0": "Bajarilmagan", "4": "Namunali"}', verbose_name='daraja izohlari')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assignments.rubric')),
            ],
            options={
                'verbose_name': 'mezon',
                'verbose_name_plural': 'mezonlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('module', models.CharField(choices=[('BIOBILIM', 'BioBilim — kasbiy bilim'), ('LAB', 'Biologik laboratoriya'), ('PEDAGOG', "Men — o'qituvchi"), ('RAQAMLI', 'Raqamli biologiya'), ('KREATIV', "Kreativ o'qituvchi")], max_length=12, verbose_name='modul')),
                ('kind', models.CharField(choices=[('LAB4', 'Laboratoriya (4 bosqichli)'), ('LESSON_PLAN', 'Dars loyihasi konstruktori'), ('CASE', 'Pedagogik keys'), ('DIGITAL', 'Raqamli mahsulot'), ('CREATIVE', 'Ijodiy topshiriq')], max_length=12, verbose_name='turi')),
                ('title', models.CharField(max_length=250, verbose_name='sarlavha')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('body', models.TextField(verbose_name='topshiriq matni')),
                ('context_note', models.TextField(blank=True, verbose_name='vaziyat / sharoit')),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], max_length=3, verbose_name='komponent')),
                ('bloom_level', models.PositiveSmallIntegerField(choices=[(1, 'Bilaman'), (2, 'Tushunaman'), (3, "Qo'llayman"), (4, 'Tahlil qilaman'), (5, 'Baholayman'), (6, 'Yarataman')], default=3, verbose_name='Bloom darajasi')),
                ('reference_solution', models.TextField(blank=True, help_text='FR-24 — faqat ish yuborilgandan keyin ochiladi.', verbose_name='etalon yechim')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='taxminiy vaqt (daq.)')),
                ('allow_files', models.BooleanField(default=True, verbose_name='fayl biriktirish')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, verbose_name='murakkablik (1-5)')),
                ('is_active', models.BooleanField(default=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assignments.rubric', verbose_name='rubrika')),
            ],
            options={
                'verbose_name': 'topshiriq',
                'verbose_name_plural': 'topshiriqlar',
                'ordering': ['module', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='javoblar')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('SELF', "O'zini baholadi"), ('SUBMITTED', 'Yuborilgan'), ('GRADED', 'Baholangan'), ('RETURNED', 'Qayta ishlashga qaytarilgan')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('self_percent', models.FloatField(blank=True, null=True, verbose_name="o'z bahosi (%)")),
                ('mentor_percent', models.FloatField(blank=True, null=True, verbose_name='mentor bahosi (%)')),
                ('mentor_feedback', models.TextField(blank=True, verbose_name='mentor fikri')),
                ('is_public', models.BooleanField(default=False, help_text='FR-36 — talaba roziligi bilan.', verbose_name="ijodiy galereyada ko'rsatish")),
                ('reopen_allowed', models.BooleanField(default=False, verbose_name='qayta yuborishga ruxsat')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ish',
                'verbose_name_plural': 'ishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('scorer', models.CharField(choices=[('SELF', "O'zini baholash"), ('MENTOR', 'Mentor bahosi')], max_length=6)),
                ('value', models.FloatField(verbose_name='ball')),
                ('comment', models.TextField(blank=True, verbose_name='izoh')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assignments.criterion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'baho',
                'verbose_name_plural': 'baholar',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=250)),
                ('size', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'biriktirilgan fayl',
                'verbose_name_plural': 'biriktirilgan fayllar',
            },
        ),
        migrations.CreateModel(
            name='CompetencyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, "Hali yo'q"), (1, 'Qisman'), (2, 'Bajara olaman')], default=0)),
                ('evidence', models.TextField(blank=True, verbose_name='dalil / havola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_checks', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='assignments.competencyitem')),
            ],
            options={
                'verbose_name': 'kompetensiya belgisi',
                'verbose_name_plural': 'kompetensiya belgilari',
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='uniq_user_competency')],
            },
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='muddat')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='assignments.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='accounts.studygroup')),
            ],
            options={
                'verbose_name': "guruh topshirig'i",
                'verbose_name_plural': 'guruh topshiriqlari',
                'constraints': [models.UniqueConstraint(fields=('assignment', 'group'), name='uniq_group_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='assignments_student_548dfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('submission', 'criterion', 'scorer'), name='uniq_score_per_scorer'),
        ),
    ]
