# Generated by Django 6.1.1 on 2026-09-09 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='muddat')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'tayinlangan topshiriq',
                'verbose_name_plural': 'tayinlangan topshiriqlar',
            },
        ),
        migrations.RemoveConstraint(
            model_name='groupassignment',
            name='uniq_group_assignment',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to='assignments.assignment'),
        ),
        migrations.DeleteModel(
            name='GroupAssignment',
        ),
    ]
