# Generated by Django 6.1.1 on 2026-09-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignedtask_and_more'),
        ('content', '0003_alter_section_options_alter_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG, PNG yoki WEBP. Vizual keysda tahlil shu tasvir asosida olib boriladi.', upload_to='assignments/visuals/%Y/%m/', verbose_name='tasvir'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Tasvirni ko'ra olmaydigan foydalanuvchi uchun qisqa tavsif.", max_length=300, verbose_name='tasvir tavsifi'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='content.section', verbose_name='fan'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='visual',
            field=models.CharField(blank=True, help_text="static/ ichidagi yo'l.", max_length=200, verbose_name='tayyor tasvir'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='kind',
            field=models.CharField(choices=[('LAB4', 'Laboratoriya (4 bosqichli)'), ('LESSON_PLAN', 'Dars loyihasi konstruktori'), ('CASE', 'Pedagogik keys'), ('DIGITAL', 'Raqamli mahsulot'), ('CREATIVE', 'Ijodiy topshiriq'), ('VISUAL', 'Muammoli vizual keys')], max_length=12, verbose_name='turi'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.CharField(choices=[('BIOBILIM', 'BioBilim — kasbiy bilim'), ('LAB', 'Biologik laboratoriya'), ('PEDAGOG', "Men — o'qituvchi"), ('RAQAMLI', 'Raqamli biologiya'), ('KREATIV', "Kreativ o'qituvchi"), ('VIZUAL', 'Muammoli vizual keyslar')], max_length=12, verbose_name='modul'),
        ),
    ]
