# Generated by Django 6.1.1 on 2026-09-15 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_alter_section_options_alter_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('PLAN', 'Tajriba rejasi'), ('DIARY', 'Kuzatuv kundaligi'), ('CALENDAR', 'Fenologik taqvim'), ('GUIDE', "Yo'riqnoma")], default='PLAN', max_length=10, verbose_name='turi')),
                ('season', models.CharField(choices=[('ALL', 'Butun yil'), ('AUTUMN', 'Kuz'), ('WINTER', 'Qish'), ('SPRING', 'Bahor'), ('SUMMER', 'Yoz')], default='ALL', max_length=10, verbose_name='mavsum')),
                ('grade', models.CharField(blank=True, help_text='Masalan: 6-sinf yoki 5–7-sinflar', max_length=40, verbose_name='sinf')),
                ('duration', models.CharField(blank=True, help_text='Masalan: 2 hafta, 1 dars', max_length=60, verbose_name='davomiyligi')),
                ('summary', models.CharField(help_text="Kartada ko'rinadigan 1-2 gap.", max_length=300, verbose_name='qisqa tavsif')),
                ('body', models.TextField(help_text="Maqsad, jihozlar, bajarish tartibi va h.k. Bo'sh qator — yangi xatboshi.", verbose_name='mazmuni')),
                ('image', models.ImageField(blank=True, upload_to='plot/images/%Y/%m/', verbose_name='rasm')),
                ('file', models.FileField(blank=True, help_text="Shablon, jadval yoki yo'riqnoma: PDF, Word, Excel, PowerPoint, rasm yoki ZIP.", upload_to='plot/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'jpg', 'jpeg', 'png', 'zip'])], verbose_name='yuklab olinadigan fayl')),
                ('url', models.URLField(blank=True, help_text="Video yoki qo'shimcha manba (ixtiyoriy).", verbose_name='tashqi havola')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'tajriba uchastkasi resursi',
                'verbose_name_plural': 'tajriba uchastkasi resurslari',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('summary', models.CharField(help_text="Kartada ko'rinadigan 1-2 gap.", max_length=300, verbose_name='qisqa tavsif')),
                ('image', models.ImageField(blank=True, help_text="JPG, PNG, WEBP yoki GIF — modelning 3D ko'rinishi (render, skrinshot).", upload_to='simulations/%Y/%m/', verbose_name='3D tasvir')),
                ('visual', models.CharField(blank=True, help_text="static/ ichidagi yo'l.", max_length=200, verbose_name='tayyor tasvir')),
                ('image_alt', models.CharField(blank=True, help_text="Tasvirni ko'ra olmaydigan foydalanuvchi uchun qisqa tavsif.", max_length=300, verbose_name='tasvir tavsifi')),
                ('body', models.TextField(blank=True, verbose_name='batafsil tavsif')),
                ('parts', models.TextField(blank=True, help_text='Har qatorda bitta: «Nomi — vazifasi». Masalan: Yadro — irsiy axborotni saqlaydi', verbose_name='asosiy qismlar')),
                ('task', models.TextField(blank=True, help_text='Har qatorda bitta savol yoki topshiriq.', verbose_name="kuzatish topshirig'i")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='content.section', verbose_name='fan')),
            ],
            options={
                'verbose_name': '3D simulyatsiya',
                'verbose_name_plural': '3D simulyatsiyalar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
