# Generated by Django 6.1.1 on 2026-09-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_section_options_alter_section_title'),
        ('development', '0002_seed_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='url',
            field=models.URLField(blank=True, help_text="Aylantirib ko'rish mumkin bo'lgan 3D model yoki video havolasi (Sketchfab, BioDigital, YouTube va h.k.). Ixtiyoriy.", verbose_name='interaktiv model havolasi'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='body',
            field=models.TextField(blank=True, help_text="Mavzuning mohiyati: model nimani ko'rsatadi, tekis rasmdan farqi nimada. Bo'sh qator — yangi xatboshi.", verbose_name='batafsil tavsif'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='image',
            field=models.ImageField(blank=True, help_text="JPG, PNG, WEBP yoki GIF — modelning 3D ko'rinishi (render, skrinshot). Real anatomik tuzilishni to'g'ri aks ettirishi shart.", upload_to='simulations/%Y/%m/', verbose_name='3D tasvir'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Rasm ostidagi qisqa tavsif: tasvirda nima va qaysi rakursda ko'rinadi. Tasvirni ko'ra olmaydigan foydalanuvchi uchun ham shu matn o'qiladi.", max_length=300, verbose_name='tasvir tavsifi'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='parts',
            field=models.TextField(blank=True, help_text="Har qatorda bitta: «Nomi — vazifasi», qisqa va lo'nda. Masalan: Yadro — irsiy axborotni saqlaydi", verbose_name='asosiy qismlar'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='section',
            field=models.ForeignKey(blank=True, help_text="Model qaysi fan (bo'lim) dasturiga tegishli — sahifada shu bo'yicha saralanadi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='content.section', verbose_name='fan'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='summary',
            field=models.CharField(help_text="Kartada ko'rinadigan 1-2 gap: model nimani va qanday ko'rinishda ko'rsatadi.", max_length=300, verbose_name='qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='task',
            field=models.TextField(blank=True, help_text="Har qatorda bitta savol. Yodlashga emas — modelni aylantirib ko'rish, qismlarni taqqoslash va sabab izlashga undasin.", verbose_name="kuzatish topshirig'i"),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='title',
            field=models.CharField(help_text="Aniq, qisqa va o'quv dasturidagi mavzu nomiga mos. Masalan: «Yurakning 3D modeli».", max_length=200, verbose_name='nomi'),
        ),
    ]
