# Generated by Django 6.1.1 on 2026-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_simulation_url_alter_simulation_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='url',
            field=models.URLField(blank=True, help_text="Aylantirib ko'rish mumkin bo'lgan 3D model yoki video havolasi (Sketchfab, BioDigital, YouTube va h.k.). Ixtiyoriy.", verbose_name='havola'),
        ),
    ]
