# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, "Nimani o'rgandim?"), (2, 'Nimani yaxshi bajardim?'), (3, 'Nimani rivojlantirishim kerak?'), (4, 'Keyingi safar nimani boshqacha qilaman?')], verbose_name="savol o'rni")),
                ('text', models.CharField(max_length=300, verbose_name='savol matni')),
                ('hint', models.CharField(blank=True, max_length=300, verbose_name='yordamchi izoh')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'refleksiya savoli',
                'verbose_name_plural': 'refleksiya savollari',
                'ordering': ['slot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('kind', models.CharField(choices=[('TASK', 'Topshiriq refleksiyasi'), ('FREE', 'Erkin yozuv'), ('GOAL', 'Maqsad yakuni')], default='TASK', max_length=6)),
                ('q1', models.TextField(blank=True, verbose_name="Nimani o'rgandim?")),
                ('q2', models.TextField(blank=True, verbose_name='Nimani yaxshi bajardim?')),
                ('q3', models.TextField(blank=True, verbose_name='Nimani rivojlantirishim kerak?')),
                ('q4', models.TextField(blank=True, verbose_name='Keyingi safar nimani boshqacha qilaman?')),
                ('free_text', models.TextField(blank=True, verbose_name='erkin matn')),
                ('tags', models.CharField(blank=True, max_length=250, verbose_name='teglar (vergul bilan)')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='sifat bali (%)')),
                ('quality_detail', models.JSONField(blank=True, default=dict, verbose_name='sifat tafsiloti')),
                ('mentor_comment', models.TextField(blank=True, verbose_name='mentor izohi')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='goals.goal')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='assignments.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refleksiya',
                'verbose_name_plural': 'refleksiya kundaligi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reflection__user_id_aa7832_idx')],
            },
        ),
    ]
