# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('fmt', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX')], default='CSV', max_length=5, verbose_name='format')),
                ('cuts', models.JSONField(blank=True, default=list, verbose_name='kesimlar')),
                ('arms', models.JSONField(blank=True, default=list, verbose_name='guruhlar')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='qatorlar soni')),
                ('filename', models.CharField(blank=True, max_length=250)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eksport',
                'verbose_name_plural': 'eksportlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('cut', models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-oraliq'), ('INTERIM_2', '2-oraliq'), ('FINAL', 'Yakuniy')], max_length=12)),
                ('arm', models.CharField(choices=[('E', 'Tajriba guruhi'), ('C', 'Nazorat guruhi'), ('N', 'Tadqiqotdan tashqari')], max_length=1)),
                ('component', models.CharField(max_length=5)),
                ('n', models.PositiveIntegerField(default=0)),
                ('mean', models.FloatField(default=0)),
                ('sd', models.FloatField(default=0)),
                ('minimum', models.FloatField(default=0)),
                ('maximum', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'statistik xulosa',
                'verbose_name_plural': 'statistik xulosalar',
                'constraints': [models.UniqueConstraint(fields=('cut', 'arm', 'component'), name='uniq_stat_summary')],
            },
        ),
    ]
