# Generated by Django 6.1.1 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='arms',
            field=models.JSONField(blank=True, default=list, verbose_name="bo'linmalar"),
        ),
        migrations.AlterField(
            model_name='statsummary',
            name='arm',
            field=models.CharField(choices=[('E', "Tajriba bo'linmasi"), ('C', "Nazorat bo'linmasi"), ('N', 'Tadqiqotdan tashqari')], max_length=1),
        ),
    ]
