# Generated by Django 6.1.1 on 2026-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_exportjob_arms_alter_statsummary_arm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsummary',
            name='cut',
            field=models.CharField(choices=[('INITIAL', "Boshlang'ich"), ('INTERIM_1', '1-chorak'), ('INTERIM_2', '2-chorak'), ('FINAL', 'Yakuniy')], max_length=12),
        ),
    ]
