# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=200, verbose_name="bo'lim")),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('icon', models.CharField(default='📚', max_length=8, verbose_name='emoji')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "bo'lim",
                'verbose_name_plural': "bo'limlar",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=250, verbose_name='dars')),
                ('slug', models.SlugField(max_length=140)),
                ('body', models.TextField(blank=True, verbose_name='dars matni')),
                ('video_url', models.URLField(blank=True, verbose_name='video havola')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='davomiyligi (daq.)')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, help_text='FR-20', verbose_name="o'zlashtirish chegarasi (%)")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='diagnostics.questionnaire', verbose_name='mustahkamlash testi')),
            ],
            options={
                'verbose_name': 'dars',
                'verbose_name_plural': 'darslar',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('kind', models.CharField(choices=[('TEXT', 'Matn'), ('IMAGE', 'Rasm'), ('VIDEO', 'Video'), ('PDF', 'PDF'), ('LINK', 'Havola')], default='TEXT', max_length=8)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='materials/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='content.lesson')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiallar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('title', models.CharField(max_length=200, verbose_name='mavzu')),
                ('slug', models.SlugField(max_length=120)),
                ('summary', models.TextField(blank=True, verbose_name='qisqacha')),
                ('component', models.CharField(choices=[('MOT', 'Motivatsion-qadriyatli'), ('COG', 'Kognitiv'), ('ACT', 'Faoliyatli-texnologik'), ('REF', 'Refleksiv'), ('CRE', 'Kreativ')], default='COG', max_length=3, verbose_name='asosiy komponent')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.section')),
            ],
            options={
                'verbose_name': 'mavzu',
                'verbose_name_plural': 'mavzular',
                'ordering': ['section', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.topic'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('status', models.CharField(choices=[('STARTED', 'Boshlangan'), ('PASSED', "O'zlashtirildi"), ('FAILED', "Qayta ko'rish kerak")], default='STARTED', max_length=8)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='test natijasi (%)')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='urinishlar')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dars natijasi',
                'verbose_name_plural': 'dars natijalari',
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson')],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('section', 'slug'), name='uniq_topic_slug_in_section'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('topic', 'slug'), name='uniq_lesson_slug_in_topic'),
        ),
    ]
