# Generated by Django 6.1.1 on 2026-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'title'], 'verbose_name': 'band', 'verbose_name_plural': 'bandlar'},
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200, verbose_name='band'),
        ),
    ]
