# Generated by Django 6.1.1 on 2026-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_section_options_alter_section_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'title'], 'verbose_name': 'fan', 'verbose_name_plural': 'fanlar'},
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200, verbose_name='fan'),
        ),
    ]
