# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="o'chirilgan sana")),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='kod')),
                ('title', models.CharField(max_length=120, verbose_name='nomi')),
                ('emoji', models.CharField(default='🏅', max_length=8, verbose_name='emoji')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('how_to_earn', models.CharField(blank=True, max_length=250, verbose_name='qanday olinadi')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'nishon',
                'verbose_name_plural': 'nishonlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('metric', models.CharField(choices=[('submissions_graded', 'Baholangan ishlar soni'), ('lab_submissions', 'Laboratoriya ishlari soni'), ('lesson_plans', 'Yaratilgan dars loyihalari'), ('creative_works', 'Ijodiy ishlar soni'), ('digital_works', 'Raqamli mahsulotlar soni'), ('reflections', 'Refleksiya yozuvlari soni'), ('lessons_passed', "O'zlashtirilgan darslar"), ('streak', 'Ketma-ket faol kunlar'), ('goals_done', 'Yakunlangan maqsadlar'), ('sdi', 'Joriy SDI (%)'), ('sdi_growth', "SDI o'sishi (foiz punkti)")], max_length=30, verbose_name='metrika')),
                ('threshold', models.FloatField(default=1, verbose_name='chegara')),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='gamification.badge')),
            ],
            options={
                'verbose_name': 'nishon qoidasi',
                'verbose_name_plural': 'nishon qoidalari',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'olingan nishon',
                'verbose_name_plural': 'olingan nishonlar',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge')],
            },
        ),
    ]
