# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('email_graded', models.BooleanField(default=True, verbose_name="baho qo'yilganda email")),
                ('email_deadline', models.BooleanField(default=True, verbose_name='muddat eslatmasi')),
                ('email_new_assignment', models.BooleanField(default=True, verbose_name='yangi topshiriq')),
                ('email_weekly', models.BooleanField(default=True, verbose_name='haftalik xulosa')),
                ('email_badge', models.BooleanField(default=False, verbose_name='nishon haqida')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bildirishnoma sozlamasi',
                'verbose_name_plural': 'bildirishnoma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('kind', models.CharField(choices=[('GRADED', 'Ishingiz baholandi'), ('DEADLINE', 'Muddat yaqinlashmoqda'), ('NEW_ASSIGNMENT', 'Yangi topshiriq'), ('WEEKLY', 'Haftalik xulosa'), ('BADGE', 'Yangi nishon'), ('MENTOR_COMMENT', 'Mentor izohi'), ('SYSTEM', 'Tizim xabari')], max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bildirishnoma',
                'verbose_name_plural': 'bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
